### PR TITLE
Update cleanupDetachedDialogs to clear body class

### PR DESCRIPTION
**Pull request by EvanSafford**
Update cleanupDetachedDialogs to clear out the ngDialog body class on <html> and <body>

https://trello.com/c/Ny59SsH2/
https://trello.com/c/1asbPvn5/
https://trello.com/c/kAk1U3cz/

### CODE REVIEW

**Comment by EvanSafford** [comment]
Tagging @eugenecyckowski for multi-platform QA

**Review by eugenecyckowski — APPROVED** [review]
works excellent!

**Comment by EvanSafford** [comment]
Tagging @danielwwong for code review

**Review by danielwwong — APPROVED** [review]
🆗 
🚢 
👍

**Pull request merged**
